config/routes.rb
Rails.application.routes.draw do
  resources :renseignements 
 get "welcome/home", to: "welcome#home"

 get 'welcome/services', to: "welcome#services"

 get 'welcome/contact', to: "welcome#contact"

 get 'welcome/connexion', to: 'welcome#connexion'

 get 'welcome/inscription', to: 'welcome#inscription'

 get 'welcome/rendezvous', to: 'welcome#rendezvous'

 get 'welcome/recapitulatif', to: 'welcome#recapitulatif'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/renseignement.rb
class Renseignement < ApplicationRecord
    validates_presence_of :email, :description
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :email, presence: true,
    uniqueness :true,
    length: {minimum: 3, maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/renseignements_controller.rb
class RenseignementsController < ApplicationController
  before_action :set_renseignement, only: %i[ show edit update destroy ]

  # GET /renseignements or /renseignements.json
  def index
    @renseignements = Renseignement.all
  end

  # GET /renseignements/1 or /renseignements/1.json
  def show
  end

  # GET /renseignements/new
  def new
    @renseignement = Renseignement.new
  end

  # GET /renseignements/1/edit
  def edit
  end

  # POST /renseignements or /renseignements.json
  def create
    @renseignement = Renseignement.new(renseignement_params)
    

    respond_to do |format|
      if @renseignement.save
        format.html { redirect_to @renseignement, notice: "Renseignement was successfully created." }
        format.json { render :show, status: :created, location: @renseignement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @renseignement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renseignements/1 or /renseignements/1.json
  def update
    respond_to do |format|
      if @renseignement.update(renseignement_params)
        format.html { redirect_to @renseignement, notice: "Renseignement was successfully updated." }
        format.json { render :show, status: :ok, location: @renseignement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @renseignement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renseignements/1 or /renseignements/1.json
  def destroy
    @renseignement.destroy
    respond_to do |format|
      format.html { redirect_to renseignements_url, notice: "Renseignement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renseignement
      @renseignement = Renseignement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def renseignement_params
      params.require(:renseignement).permit(:entreprise, :string, :particulier, :string, :email, :string, :numero, :string, :description, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
    def home
    end

    def services
    end

    def contact 
     @renseignement = Renseignement.new
     
    end

    def connexion

    end

    def inscription
        
    end

    def rendezvous 

    end

    def recapitulatif
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/renseignements_helper.rb
module RenseignementsHelper
end

app/helpers/tableaus_helper.rb
module TableausHelper
end

app/views/layouts/_footer.html.erb
<div class='container'>
    <footer>
        <small>
            <p>© We Wash Eco company by Florence Gomis</p>
        <small>
    </footer>
</div>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><%= link_to "We Wash Eco", welcome_home_path %></li>
  <li role="presentation"><%= link_to "Home",  welcome_home_path  %></li>
  <li role="presentation"><%= link_to "Services",  welcome_services_path %></li>
  <li role="presentation"><%= link_to "Contact",  welcome_contact_path %></li>
  <div align='end'>
  <li role="presentation"><%= link_to "Connexion",  welcome_connexion_path %></li>
  <li role="presentation"><%= link_to "Inscription",  welcome_inscription_path %></li>
  </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Washeco</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gluten:wght@100&display=swap" rel="stylesheet">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/renseignements/_form.html.erb
<%= form_with(model: renseignement, local: true) do |form| %>
  <% if renseignement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(renseignement.errors.count, "error") %> prohibited this renseignement from being saved:</h2>

      <ul>
        <% renseignement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :entreprise %>
    <%= form.text_field :entreprise %>
  </div>

  <div class="field">
    <%= form.label :particulier %>
    <%= form.text_field :particulier %>
  </div>


  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>


  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/renseignements/edit.html.erb
<h1>Editing Renseignement</h1>

<%= render 'form', renseignement: @renseignement %>

<%= link_to 'Show', @renseignement %> |
<%= link_to 'Back', renseignements_path %>

app/views/renseignements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Renseignements</h1>

<table>
  <thead>
    <tr>
      <th>Entreprise</th>
      <th>Particulier</th>
      <th>Email</th>
      <th>Numero</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @renseignements.each do |renseignement| %>
      <tr>
        <td><%= renseignement.entreprise %></td>
        <td><%= renseignement.particulier %></td>
        <td><%= renseignement.email %></td>
        <td><%= renseignement.numero %></td>
        <td><%= renseignement.description %></td>
        <td><%= link_to 'Show', renseignement %></td>
        <td><%= link_to 'Edit', edit_renseignement_path(renseignement) %></td>
        <td><%= link_to 'Destroy', renseignement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Renseignement', new_renseignement_path %>

app/views/renseignements/new.html.erb
<h1>New Renseignement</h1>

<%= render 'form', renseignement: @renseignement %>

<%= link_to 'Back', renseignements_path %>

app/views/renseignements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entreprise:</strong>
  <%= @renseignement.entreprise %>
</p>

<p>
  <strong>Particulier:</strong>
  <%= @renseignement.particulier %>
</p>


<p>
  <strong>Email:</strong>
  <%= @renseignement.email %>
</p>



<p>
  <strong>Numero:</strong>
  <%= @renseignement.numero %>
</p>


<p>
  <strong>Description:</strong>
  <%= @renseignement.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @renseignement.text %>
</p>

<%= link_to 'Edit', edit_renseignement_path(@renseignement) %> |
<%= link_to 'Back', renseignements_path %>

app/views/welcome/connexion.html.erb
<h1> Connexion </h1>

<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We ll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/welcome/contact.html.erb
<h1>Devis</h1>

<div>
<%= form_with model: @renseignement  do |form| %>
    <div>
    <%= form.radio_button :entreprise, 'Entreprise' %>entreprise<br />
    <%= form.radio_button :particulier, 'Particulier' %>particulier<br />
    </div>
    <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :numero %><br>
    <%= form.telephone_field :numero%>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: "70x5" %>
  </div>

  <div>
    <%= form.submit "Envoyer" %>
  </div>
<% end %>
</div>

app/views/welcome/home.html.erb
<h1 align="center"> We wash eco </h1>

<div class="jumbotron">

</div>

app/views/welcome/inscription.html.erb
<h1> Inscription </h1>

<form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <label for="validationCustom01">First name</label>
      <input type="text" class="form-control" id="validationCustom01" placeholder="First name" value="Mark" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationCustom02">Last name</label>
      <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationCustomUsername">Username</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend">@</span>
        </div>
        <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>
        <div class="invalid-feedback">
          Please choose a username.
        </div>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label for="validationCustom03">City</label>
      <input type="text" class="form-control" id="validationCustom03" placeholder="City" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <label for="validationCustom04">State</label>
      <input type="text" class="form-control" id="validationCustom04" placeholder="State" required>
      <div class="invalid-feedback">
        Please provide a valid state.
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <label for="validationCustom05">Zip</label>
      <input type="text" class="form-control" id="validationCustom05" placeholder="Zip" required>
      <div class="invalid-feedback">
        Please provide a valid zip.
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
      <label class="form-check-label" for="invalidCheck">
        Agree to terms and conditions
      </label>
      <div class="invalid-feedback">
        You must agree before submitting.
      </div>
    </div>
  </div>
  <button class="btn btn-primary" type="submit">Submit form</button>
</form>

app/views/welcome/recapitulatif.html.erb
<h1> Recapitulatif </h1>

app/views/welcome/rendezvous.html.erb
<h1> Prise de rendez-vous </h1>

app/views/welcome/services.html.erb
<h1 align="center"> Services </h1>

<p> Que proposons-nous ?<p>

<div class='image1 shadow p-3 mb-5 bg-body rounded'>
</div>
<p> Le saviez-vous ? Tous les ans c est plus de 50 000L d'eau qui sont gaspillés de par l usage des lavages auto classiques.</p>